name: Markdown Links

on: 
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    #paths:
    #  - '.github/**'
    #  - 'docs/**'
    #  - '*.md'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        folder-path: ./docs
        file-path: ./README.md ./LICENSE.md ./CHANGELOG.md
